In [5]:
#numpy

import numpy as np
l1=3
l2=[2,3]
n1=np.array(l1)
n2=np.array(l2)

In [7]:
print(type(n1))
print(type(n2))
print(type(l2))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'list'>


In [6]:
print(l2)
print(n2)

[2, 3]
[2 3]


In [9]:
#multidimensional array
#note:the argument is a list containing two sub-lists
#arr1=np.array([[2,3,5], [3,5,7]])
l1=[2,3,5]
l2=[3,5,7]
arr1=np.array([l1, l2])
print(arr1)



[[2 3 5]
 [3 5 7]]


In [12]:
n1= np.zeros((1,2))
print(n1)

[[0. 0.]]


In [13]:
n2=np.zeros((3,3))
print(n2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
n3=np.full((2,2),10)
print(n3)

[[10 10]
 [10 10]]


In [17]:
#initialize array with a range of numbers
#1st argument is including and 2nd argument is excluding
n3=np.arange(10,20)
print(n3)

[10 11 12 13 14 15 16 17 18 19]


In [20]:
#specifying step size for initializing
n4=np.arange(10,30,2)
print(n4)

[10 12 14 16 18 20 22 24 26 28]


In [24]:
#initializing with random integers
n2=np.random.randint(1,100,5)
print(n2)

[ 5 81 54 75  3]


In [25]:
arr1=np.array([[2,3,5],[3,5,7]])

In [26]:
print(arr1)

[[2 3 5]
 [3 5 7]]


In [43]:
#no of dimensions
print(arr1.ndim)
#shape of array
print(arr1.shape)
#no. of elements
print(arr1.size)
#length of first dimension
print(len(arr1))
print(arr1)
#reshape the array
print(arr1.reshape((3,2)))
#print(arr1)
print(len(arr1.reshape((3,2))))

1
(3,)
3
3
[2 3 5]


ValueError: cannot reshape array of size 3 into shape (3,2)

In [31]:
#additon of numpy
arr1=np.array([10,20])
arr2=np.array([30,40])

#arr3=np.array([35,45])
np.sum([arr1,arr2])

100

In [32]:
np.sum([arr1,arr2],axis=0)

array([40, 60])

In [33]:
np.sum([arr1,arr2],axis=1)

array([30, 70])

In [37]:
#joining two array in three different ways
#vstack, hstack and column stack
arr1=np.array([2,3,5])
arr2=np.array([3,5,6])
arr3=np.vstack((arr1,arr2))
arr4=np.hstack((arr1,arr2))
arr5=np.column_stack((arr1,arr2))

print(arr3)
print()
print(arr4)
print()
print(arr5)

[[2 3 5]
 [3 5 6]]

[2 3 5 3 5 6]

[[2 3]
 [3 5]
 [5 6]]
